version: "3.9"

services:

  postgres:
    container_name: store_db
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: fakestore
    ports:
      - "5432:5432"
    volumes:
      - ./database/init:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data

  backend:
    container_name: nest_backend
    build: ./backend
    restart: always
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://admin:admin123@postgres:5432/fakestore
    ports:
      - "3000:3000"

  frontend:
    container_name: react_frontend
    build: ./frontend
    restart: always
    depends_on:
      - backend
    ports:
      # Puerto 80 por el servidor web Nginx
      - "5173:80"   

volumes:
  postgres_data:
